version: '3'
services: 
    app:
        container_name: docker-node-mysql
        restart: always
        build: .
        env_file:
            - ./.env
        depends_on:
            - "${DATABASE_HOST}"
        volumes:
            - .:/app
        ports: 
            - "${API_PORT}:${API_PORT}"
    db:
        container_name: mysql
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db_dump:/docker-entrypoint-initdb.d
        env_file:
            - ./.env
        ports:
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
    db1:
        build: ./database
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "4306:3306"
        env_file:
            - ./.env